const{signin,signup}=require('../controller/admin/auth.js')
const {isValidatedRequest,validateRequest,validatesigninRequest, isAdmin, required,upload,upload1}=require('../controller/vlaidate')
const {addCatagory,getCatagory,addProducts,addcat,getcart}=require('../controller/admin/addCatagory')
const {deleteProduct}=require('../controller/admin/DeleteProduct')
const {getusers}=require('../controller/admin/Getusers')
const {getProduct}=require('../controller/getProduct')
const {UpdateProduct}=require('../controller/admin/EditProduct')
const express=require('express')
const router=express.Router()
router.post('/admin/signin',validatesigninRequest,isValidatedRequest ,signin)
router.post('/admin/signup',validateRequest,isValidatedRequest,signup)
router.post('/admin/addCatagory',required, isAdmin,upload1.single('img') ,addCatagory)
router.post('/admin/products/create',required,isAdmin,upload.array('productPicture') ,addProducts)
router.get('/getCatagories',getCatagory)
router.get('/getProduct',getProduct)
router.put('/admin/product/update',required,isAdmin,UpdateProduct)
router.delete('/admin/product/delete',required,isAdmin,deleteProduct)
module.exports=router